### ISSUE TITLE
Connection not secure

### ISSUE THREAD

**Issue by pvanlaet** [openmotics/gateway-frontend#14]
When connecting to the Gateway using Firefox v50 the following is shown:

> Your connection is not secure
> The owner of 192.168.0.126 has configured their web site improperly. To protect your information from being stolen, Firefox has not connected to this web site.

The user needs to click the `Advanced` tab and then sees:

>192.168.0.126 uses an invalid security certificate.
> The certificate is not trusted because it is self-signed.
> The certificate is not valid for the name 192.168.0.126.
> Error code: SEC_ERROR_UNKNOWN_ISSUER

After clicking `Add Exception` and `Confirm Security Exception` in the following pop-up the login page is shown.

Is there a way to improve this?

**Comment by khenderick** [comment]
While it's technically possible to make a valid certificate for an ip address, I don't think it makes a lot of sense to provide this somehow as the ip address of customers might change every now and then.

An option would be to provide e.g. a subdomain ```xxxxxx.gateway.openmotics.com``` or sth similar where we keep an ```A``` record pointing to a customer's gateway, and generate valid SSL certificates for that domain. However, again this might lead to trouble if the assigned ip address changes in the customer's network. It might work for 90% of the customers though.

I'll leave this open for giving it a bit more thinking.

**Comment by khenderick** [comment]
I for myself have configured my router to assign a fixed ip address to the Gateway, and have a subdomain of one of my domains assigned to the Gateway's ip address. My NAS automatically maintains a "Let's encrypt" certificate and uploads it to my gateway. So the idea does work.
