### ISSUE TITLE
Setup wizard missing

### ISSUE THREAD

**Issue by pvanlaet** [openmotics/gateway-frontend#22]
In the cloud UI the Settings and Configuration sections are separated and the latter is structured in such a way that the user is guided through the process. In the local UI these sections are mixed and it is not clear to the user on how to quickly get things up and running.
In order to aid the user in the setup and in a way that requires the minimum amount of work I would propose the following:

1. When a user logs in to a "clean install" (nothing yet configured): ask him if he would like to start the setup. This can be through a notification bar at the top of the Dashboard or even a pop-up. Should include a link to the first part of the "wizard".

2. Split up Settings and add a Configuration section (or add Configuration indented under Settings) with the relevant sections indented under it.

3. Split up Environment and Initialisation. Environment should include the same fields as the Configuration > General page.

4. Add the following items under Configuration **in this order**:
   - General
   - Initialisation
   - Outputs
   - Inputs
   - Sensors
   - Thermostats

   Each of these pages should at least contain some explanatory text at the top, like the one on the cloud UI

5. Add a "next" button at the bottom of each page under Configuration so a flow is created

**Comment by pvanlaet** [comment]
@pilaar
This one should really be looked at in some way or form since the local UI will mostly be used to set up the system when no internet conn is available. Incorporating the tools to aid the user in setting up the system without additional manual or wiki pages (remember: no internet available) is key here.

**Comment by khenderick** [comment]
As discussed, this ticket is now considered to be resolved. In the future, we might add a real wizard to guide a user through the setup in a later stage. At this moment, we give the user enough pointers to figure out what to do.
