### ISSUE TITLE
Group Action trash no function

### ISSUE THREAD

**Issue by pvanlaet** [openmotics/gateway-frontend#26]
![image](https://cloud.githubusercontent.com/assets/7603855/20906247/5e045e40-bb47-11e6-8782-c3db829d15fe.png)

The large trash can in the right bottom corner doesn't do anything when I drop a control onto it.
What should this do?

Firefox v50 Win10

**Comment by khenderick** [comment]
Unfortunately it doesn't work quite good, seems to be an upstream problem. I'll remove the trash can awaiting a fix.
